from investment_portfolio.views.portfolio.portfolio_create_views import PortfolioCreateView
from investment_portfolio.views.portfolio.portfolio_list_view import portfolio_list
from investment_portfolio.views.portfolio.portfolio_edit_view import PortfolioEditView
