# Generated by Django 5.0.7 on 2024-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_portfolio', '0005_user_is_staff_user_is_superuser_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('instrument_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('fund', 'Fund')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
