# Generated by Django 5.0.7 on 2024-07-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_portfolio', '0008_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_portfolio.portfolio'),
        ),
    ]
