# Generated by Django 5.0.7 on 2025-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='instrument',
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FinancialInstrument',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
